version: "3"

services:
  mongo:
    image: mongo:latest
    container_name: univerdustry_mongo
    command: --quiet
    environment:
      - MONGO_INITDB_ROOT_USERNAME=univerdustry
      - MONGO_INITDB_ROOT_PASSWORD=univerdustry
    networks:
      - net_mongo
    volumes:
      - data_mongo:/data/db
    ports:
      - "27017:27017"
  mongo_rest:
    build: ./mongo_rest
    container_name: univerdustry_mongo_rest
    command: ["python3", "./run.py"]
    ports:
      - "6000:6000"
    volumes:
      - data_log:/application/logs
    networks:
      - net_mongo
      - net_mongo_rest
    depends_on:
      - mongo
    environment:
      - LANG=tr_TR.UTF-8
      - LANGUAGE=tr_TR:tr
      - LC_ALL=tr_TR.UTF-8
      - TZ=Europe/Istanbul
      - EXPOSE_PORT=6000
      - FLASK_APP=application/app
      - FLASK_ENV=development
      - FILE_LOG_LEVEL=DEBUG
      - CONSOLE_LOG_LEVEL=INFO
      - MONGO_URI=mongodb://univerdustry:univerdustry@univerdustry_mongo:27017/
  gateway:
    build: ./gateway
    container_name: univerdustry_gateway
    command: ["python3", "./run.py"]
    volumes:
      - data_log:/application/logs
    ports:
      - "7000:7000"
    networks:
      - net_mongo_rest
      - net_elasticsearch
    depends_on:
      - mongo_rest
    environment:
      - LANG=tr_TR.UTF-8
      - LANGUAGE=tr_TR:tr
      - LC_ALL=tr_TR.UTF-8
      - TZ=Europe/Istanbul
      - EXPOSE_PORT=7000
      - FLASK_APP=application/app
      - FLASK_ENV=development
      - FILE_LOG_LEVEL=DEBUG
      - CONSOLE_LOG_LEVEL=INFO
      - MONGO_REST=http://univerdustry_mongo_rest:6000
      - ELASTICSEARCH=http://univerdustry_elasticsearch:9200
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.0.1
    container_name: univerdustry_elasticsearch
    volumes:
      - ./elasticsearch/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
    ports:
      - "9200:9200"
      - "9300:9300"
    networks:
      - net_elasticsearch
    environment:
      ES_JAVA_OPTS: "-Xmx256m -Xms256m"
  kibana:
    image: docker.elastic.co/kibana/kibana:6.0.1
    container_name: univerdustry_kibana
    volumes:
      - ./kibana/:/usr/share/kibana/config/
    ports:
      - "5601:5601"
    networks:
      - net_elasticsearch
    depends_on:
      - elasticsearch
  redis:
    image: bitnami/redis:latest
    container_name: univerdustry_redis
    ports:
      - "6379:6379"
    volumes:
      - data_redis:/bitnami
    networks:
      - net_worker
    environment:
      - LANG=tr_TR.UTF-8
      - LANGUAGE=tr_TR:tr
      - LC_ALL=tr_TR.UTF-8
      - TZ=Europe/Istanbul
      - ALLOW_EMPTY_PASSWORD=yes
      - DISABLE_COMMANDS=FLUSHDB,FLUSHALL,CONFIG
  flower:
    image: mher/flower
    container_name: univerdustry_flower
    networks:
      - net_worker
    ports:
      - "5555:5555"
    depends_on:
      - redis
    environment:
      - LANG=tr_TR.UTF-8
      - LANGUAGE=tr_TR:tr
      - LC_ALL=tr_TR.UTF-8
      - CELERY_BROKER_URL=redis://univerdustry_redis:6379/0
      - FLOWER_BROKER_URL=redis://univerdustry_redis:6379/0
      - TZ=Europe/Istanbul
      - FLOWER_PORT=5555
  vectorizer:
    build: ./vectorizer
    container_name: univerdustry_vectorizer
    command: ["python3", "./run.py"]
    volumes:
      - data_log:/application/logs
      - data_embeddings:/application/embeddings
    ports:
      - "9000:9000"
    networks:
      - net_worker
    environment:
      - LANG=tr_TR.UTF-8
      - LANGUAGE=tr_TR:tr
      - LC_ALL=tr_TR.UTF-8
      - TZ=Europe/Istanbul
      - EXPOSE_PORT=9000
      - FLASK_APP=application/app
      - FLASK_ENV=development
      - FILE_LOG_LEVEL=DEBUG
      - CONSOLE_LOG_LEVEL=INFO
  schedule_worker:
    build: ./worker
    container_name: univerdustry_schedule_worker
    command: ["celery", "beat", "-A", "application.celery", "--loglevel=debug"]
    volumes:
      - data_log:/application/logs
      - data_worker:/application/files
    networks:
      - net_worker
      - net_mongo_rest
      - net_elasticsearch
    depends_on:
      - redis
    environment:
      - LANG=tr_TR.UTF-8
      - LANGUAGE=tr_TR:tr
      - LC_ALL=tr_TR.UTF-8
      - CELERY_BROKER_URL=redis://univerdustry_redis:6379/0
      - TZ=Europe/Istanbul
      - FLASK_ENV=development
      - FILE_LOG_LEVEL=DEBUG
      - CONSOLE_LOG_LEVEL=INFO
      - MONGO_REST=http://univerdustry_mongo_rest:6000
      - ELASTICSEARCH=http://univerdustry_elasticsearch:9200
  worker_1:
    build: ./worker
    container_name: univerdustry_worker_1
    command: ["celery", "worker", "-A", "application.celery", "-P", "eventlet", "--loglevel=info", "-n",
              "worker_1"]
    volumes:
      - data_log:/application/logs
      - data_worker:/application/files
    networks:
      - net_worker
      - net_mongo_rest
      - net_elasticsearch
    depends_on:
      - redis
      - mongo_rest
      - elasticsearch
    environment:
      - LANG=tr_TR.UTF-8
      - LANGUAGE=tr_TR:tr
      - LC_ALL=tr_TR.UTF-8
      - CELERY_BROKER_URL=redis://univerdustry_redis:6379/0
      - TZ=Europe/Istanbul
      - FLASK_ENV=development
      - FILE_LOG_LEVEL=DEBUG
      - CONSOLE_LOG_LEVEL=INFO
      - MONGO_REST=http://univerdustry_mongo_rest:6000
      - ELASTICSEARCH=http://univerdustry_elasticsearch:9200
  worker_2:
    build: ./worker
    container_name: univerdustry_worker_2
    command: ["celery", "worker", "-A", "application.celery", "-P", "eventlet", "--loglevel=info", "-n",
              "worker_2"]
    volumes:
      - data_log:/application/logs
      - data_worker:/application/files
    networks:
      - net_worker
      - net_mongo_rest
      - net_elasticsearch
    depends_on:
      - redis
      - mongo_rest
      - elasticsearch
    environment:
      - LANG=tr_TR.UTF-8
      - LANGUAGE=tr_TR:tr
      - LC_ALL=tr_TR.UTF-8
      - CELERY_BROKER_URL=redis://univerdustry_redis:6379/0
      - TZ=Europe/Istanbul
      - FLASK_ENV=development
      - FILE_LOG_LEVEL=DEBUG
      - CONSOLE_LOG_LEVEL=INFO
      - MONGO_REST=http://univerdustry_mongo_rest:6000
      - ELASTICSEARCH=http://univerdustry_elasticsearch:9200
#  worker_3:
#    build: ./worker
#    container_name: univerdustry_worker_3
#    command: ["celery", "worker", "-A", "application.celery", "-P", "eventlet", "--loglevel=info", "-n",
#              "worker_3"]
#    volumes:
#      - data_log:/application/logs
#      - data_worker:/application/files
#    networks:
#      - net_worker
#      - net_mongo_rest
#      - net_elasticsearch
#    depends_on:
#      - redis
#      - mongo_rest
#      - elasticsearch
#    environment:
#      - LANG=tr_TR.UTF-8
#      - LANGUAGE=tr_TR:tr
#      - LC_ALL=tr_TR.UTF-8
#      - CELERY_BROKER_URL=redis://univerdustry_redis:6379/0
#      - TZ=Europe/Istanbul
#      - FLASK_ENV=development
#      - FILE_LOG_LEVEL=DEBUG
#      - CONSOLE_LOG_LEVEL=INFO
#      - MONGO_REST=http://univerdustry_mongo_rest:6000
#      - ELASTICSEARCH=http://univerdustry_elasticsearch:9200
#  worker_4:
#    build: ./worker
#    container_name: univerdustry_worker_4
#    command: ["celery", "worker", "-A", "application.celery", "-P", "eventlet", "--loglevel=info", "-n",
#              "worker_4"]
#    volumes:
#      - data_log:/application/logs
#      - data_worker:/application/files
#    networks:
#      - net_worker
#      - net_mongo_rest
#      - net_elasticsearch
#    depends_on:
#      - redis
#      - mongo_rest
#      - elasticsearch
#    environment:
#      - LANG=tr_TR.UTF-8
#      - LANGUAGE=tr_TR:tr
#      - LC_ALL=tr_TR.UTF-8
#      - CELERY_BROKER_URL=redis://univerdustry_redis:6379/0
#      - TZ=Europe/Istanbul
#      - FLASK_ENV=development
#      - FILE_LOG_LEVEL=DEBUG
#      - CONSOLE_LOG_LEVEL=INFO
#      - MONGO_REST=http://univerdustry_mongo_rest:6000
#      - ELASTICSEARCH=http://univerdustry_elasticsearch:9200
#  worker_5:
#    build: ./worker
#    container_name: univerdustry_worker_5
#    command: ["celery", "worker", "-A", "application.celery", "-P", "eventlet", "--loglevel=info", "-n",
#              "worker_5"]
#    volumes:
#      - data_log:/application/logs
#      - data_worker:/application/files
#    networks:
#      - net_worker
#      - net_mongo_rest
#      - net_elasticsearch
#    depends_on:
#      - redis
#      - mongo_rest
#      - elasticsearch
#    environment:
#      - LANG=tr_TR.UTF-8
#      - LANGUAGE=tr_TR:tr
#      - LC_ALL=tr_TR.UTF-8
#      - CELERY_BROKER_URL=redis://univerdustry_redis:6379/0
#      - TZ=Europe/Istanbul
#      - FLASK_ENV=development
#      - FILE_LOG_LEVEL=DEBUG
#      - CONSOLE_LOG_LEVEL=INFO
#      - MONGO_REST=http://univerdustry_mongo_rest:6000
#      - ELASTICSEARCH=http://univerdustry_elasticsearch:9200

volumes:
  data_log:
  data_mongo:
  data_redis:
  data_worker:
  data_embeddings:

networks:
  net_mongo:
  net_worker:
  net_mongo_rest:
  net_elasticsearch:
