version: "3"

services:
  vectorizer:
    build: ./vectorizer
    container_name: univerdustry_vectorizer
    command: ["python3", "./run.py"]
    ports:
      - "9000:9000"
    environment:
      - LANG=tr_TR.UTF-8
      - LANGUAGE=tr_TR:tr
      - LC_ALL=tr_TR.UTF-8
      - TZ=Europe/Istanbul
      - EXPOSE_PORT=9000
      - FLASK_APP=application/app
      - FLASK_ENV=production
      - FILE_LOG_LEVEL=DEBUG
      - CONSOLE_LOG_LEVEL=INFO
