version: "3.8"

services:
  vectorizer:
    build: ./vectorizer
    container_name: vectorizer
    command: ["python3", "./run.py"]
    volumes:
      - ./embeddings:/embeddings:ro,shared
    ports:
      - "9005:9005"
    environment:
      - LANG=tr_TR.UTF-8
      - LANGUAGE=tr_TR:tr
      - LC_ALL=tr_TR.UTF-8
      - TZ=Europe/Istanbul
      - EXPOSE_PORT=9005
      - FILE_LOG_LEVEL=DEBUG
      - CONSOLE_LOG_LEVEL=INFO
