version: '3'

services:
  database:
    build: ./database
    volumes:
      - "db_data:/var/lib/postgresql/9.5/main"
    env_file:
      - env_file
    networks:
      - db_nw
    ports:
      - "5432:5432"
    env_file:
      - env_file
  database_rest:
    build: ./postgrest
    ports:
      - "3000:3000"
    networks:
      - db_nw
    env_file:
      - env_file
    depends_on:
      - database
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.4.2
    volumes:
      - ./elasticsearch/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
    ports:
      - "9200:9200"
      - "9300:9300"
    networks:
      - search_nw
    env_file:
      - env_file
  kibana:
    image: docker.elastic.co/kibana/kibana:6.0.1
    volumes:
      - ./kibana:/usr/share/kibana/config/
    ports:
      - "5601:5601"
    networks:
      - search_nw
    env_file:
      - env_file
    depends_on:
      - elasticsearch
  redis:
    image: 'bitnami/redis:latest'
    ports:
      - "6379:6379"
    networks:
      - app_nw
    volumes:
      - 'redis_data:/bitnami'
    env_file:
      - env_file
  operator:
    build: ./operator
    env_file:
      - env_file
    ports:
      - 6000:6000
    networks:
      - db_nw
      - app_nw
      - search_nw
    depends_on:
      - database_rest
  scraper:
    build: ./scraper
    env_file:
      - env_file
    ports:
      - 7000:7000
    networks:
      - app_nw
    depends_on:
      - operator
  worker:
    build: ./worker
    env_file:
      - env_file
    networks:
      - db_nw
      - app_nw
      - search_nw
    env_file:
      - env_file
    depends_on:
      - redis
  flower:
    image: zoomeranalytics/flower:0.9.1-4.0.2
    networks:
      - app_nw
    env_file:
      - env_file
    ports:
      - "5555:5555"
    env_file:
      - env_file
    depends_on:
      - redis

networks:
  app_nw:
  db_nw:
  search_nw:

volumes:
  db_data:
  redis_data:
