version: "3.8"

services:
  vectorizer:
    build: ./vectorizer
    container_name: vectorizer
    command: ["python3", "./run.py"]
    volumes:
      - ./embeddings:/embeddings
    networks:
      - net_app
    ports:
      - "9000:9000"
    environment:
      - LANG=tr_TR.UTF-8
      - LANGUAGE=tr_TR:tr
      - LC_ALL=tr_TR.UTF-8
      - TZ=Europe/Istanbul
      - EXPOSE_PORT=9000
      - FLASK_APP=application/app
      - FLASK_ENV=development
      - FILE_LOG_LEVEL=DEBUG
      - CONSOLE_LOG_LEVEL=INFO

networks:
  net_app: