version: "3"

services:
  database:
    build: ./database
    container_name: univerdustry_database
    networks:
      - db_nw
    volumes:
      - db_data:/var/lib/postgresql/9.5/main
    ports:
      - "5432:5432"
  database_rest:
    build: ./database_rest
    container_name: univerdustry_database_rest
    networks:
      - db_nw
    ports:
      - "6000:6000"
    environment:
      - EXPOSE_PORT=6000
      - FLASK_ENV=development
      - SQLALCHEMY_DATABASE_URI=postgres://univerdustry:univerdustry@database:5432/univerdustry
  redis:
    image: bitnami/redis:latest
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/bitnami
    environment:
      - LANG=tr_TR.UTF-8
      - LANGUAGE=tr_TR:tr
      - LC_ALL=tr_TR.UTF-8
      - TZ=Europe/Istanbul
      - ALLOW_EMPTY_PASSWORD=yes
      - DISABLE_COMMANDS=FLUSHDB,FLUSHALL,CONFIG


volumes:
  db_data:
  redis_data:

networks:
  db_nw:
