version: "3"

services:
  mongo:
    image: mongo:latest
    container_name: mongo
    command: --quiet
    restart: always
    environment:
      - MONGO_INITDB_ROOT_USERNAME=univerdustry
      - MONGO_INITDB_ROOT_PASSWORD=univerdustry
    networks:
      - net_mongo
    volumes:
      - data_mongo:/data/db
    ports:
      - "27017:27017"
  mongo_rest:
    build: ./mongo_rest
    container_name: mongo_rest
    command: ["python3", "./run.py"]
    ports:
      - "9000:9000"
    volumes:
      - data_log:/application/logs
    networks:
      - net_mongo
      - net_mongo_rest
    depends_on:
      - mongo
    environment:
      - LANG=tr_TR.UTF-8
      - LANGUAGE=tr_TR:tr
      - LC_ALL=tr_TR.UTF-8
      - TZ=Europe/Istanbul
      - EXPOSE_PORT=9000
      - FLASK_APP=application/app
      - FLASK_ENV=development
      - FILE_LOG_LEVEL=DEBUG
      - CONSOLE_LOG_LEVEL=INFO
      - MONGO_URI=mongodb://univerdustry:univerdustry@mongo:27017/
  gateway:
    build: ./gateway
    container_name: gateway
    command: ["python3", "./run.py"]
    volumes:
      - data_log:/application/logs
    ports:
      - "9001:9001"
    networks:
      - net_elasticsearch
      - net_mongo_rest
    depends_on:
      - mongo_rest
      - elasticsearch
    environment:
      - LANG=tr_TR.UTF-8
      - LANGUAGE=tr_TR:tr
      - LC_ALL=tr_TR.UTF-8
      - TZ=Europe/Istanbul
      - EXPOSE_PORT=9001
      - FLASK_APP=application/app
      - FLASK_ENV=development
      - FILE_LOG_LEVEL=DEBUG
      - CONSOLE_LOG_LEVEL=INFO
      - MONGO_REST=http://mongo_rest:9000
      - ELASTICSEARCH=http://elasticsearch:9200
      - VECTORIZER=http://projecttest.westeurope.cloudapp.azure.com:9005
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.6.2
    container_name: elasticsearch
    restart: always
    volumes:
      - ./elasticsearch/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
    ports:
      - "9200:9200"
      - "9300:9300"
    networks:
      - net_elasticsearch
    environment:
      ES_JAVA_OPTS: "-Xmx256m -Xms256m"
  kibana:
    image: docker.elastic.co/kibana/kibana:7.6.2
    container_name: kibana
    volumes:
      - ./kibana/:/usr/share/kibana/config/
    ports:
      - "5601:5601"
    networks:
      - net_elasticsearch
    depends_on:
      - elasticsearch
  redis:
    image: bitnami/redis:latest
    container_name: redis
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - data_redis:/bitnami
    networks:
      - net_worker
    environment:
      - LANG=tr_TR.UTF-8
      - LANGUAGE=tr_TR:tr
      - LC_ALL=tr_TR.UTF-8
      - TZ=Europe/Istanbul
      - ALLOW_EMPTY_PASSWORD=yes
      - DISABLE_COMMANDS=FLUSHDB,FLUSHALL,CONFIG
  flower:
    image: mher/flower
    container_name: flower
    networks:
      - net_worker
    ports:
      - "9003:9003"
    depends_on:
      - redis
    environment:
      - LANG=tr_TR.UTF-8
      - LANGUAGE=tr_TR:tr
      - LC_ALL=tr_TR.UTF-8
      - CELERY_BROKER_URL=redis://redis:6379/0
      - FLOWER_BROKER_URL=redis://redis:6379/0
      - TZ=Europe/Istanbul
      - FLOWER_PORT=9003
  apache_tika:
    image: apache/tika:latest
    container_name: apache_tika
    restart: always
    networks:
      - net_worker
    ports:
      - "9998:9998"
  schedule_worker:
    build: ./worker
    container_name: schedule_worker
    command: ["celery", "beat", "-A", "application.celery", "--loglevel=debug"]
    restart: always
    volumes:
      - data_log:/application/logs
      - data_worker:/application/files
    networks:
      - net_worker
      - net_mongo_rest
      - net_elasticsearch
    depends_on:
      - redis
    environment:
      - LANG=tr_TR.UTF-8
      - LANGUAGE=tr_TR:tr
      - LC_ALL=tr_TR.UTF-8
      - CELERY_BROKER_URL=redis://redis:6379/0
      - TZ=Europe/Istanbul
      - FLASK_ENV=development
      - FILE_LOG_LEVEL=DEBUG
      - CONSOLE_LOG_LEVEL=INFO
      - MONGO_REST=http://mongo_rest:9000
      - ELASTICSEARCH=http://elasticsearch:9200
      - VECTORIZER=http://projecttest.westeurope.cloudapp.azure.com:9005
      - APACHE_TIKA=http://apache_tika:9998
  worker_1:
    build: ./worker
    container_name: worker_1
    command: ["celery", "worker", "-A", "application.celery", "-P", "eventlet", "--loglevel=info", "-n",
              "worker_1"]
    volumes:
      - data_log:/application/logs
      - data_worker:/application/files
    networks:
      - net_worker
      - net_mongo_rest
      - net_elasticsearch
    depends_on:
      - redis
      - gateway
      - elasticsearch
    environment:
      - FIRST=true
      - LANG=tr_TR.UTF-8
      - LANGUAGE=tr_TR:tr
      - LC_ALL=tr_TR.UTF-8
      - CELERY_BROKER_URL=redis://redis:6379/0
      - TZ=Europe/Istanbul
      - FLASK_ENV=development
      - FILE_LOG_LEVEL=DEBUG
      - CONSOLE_LOG_LEVEL=INFO
      - MONGO_REST=http://mongo_rest:9000
      - ELASTICSEARCH=http://elasticsearch:9200
      - VECTORIZER=http://projecttest.westeurope.cloudapp.azure.com:9005
      - APACHE_TIKA=http://apache_tika:9998
  worker_2:
    build: ./worker
    container_name: worker_2
    command: ["celery", "worker", "-A", "application.celery", "-P", "eventlet", "--loglevel=info", "-n",
              "worker_2"]
    volumes:
      - data_log:/application/logs
      - data_worker:/application/files
    networks:
      - net_worker
      - net_mongo_rest
      - net_elasticsearch
    depends_on:
      - redis
      - gateway
    environment:
      - LANG=tr_TR.UTF-8
      - LANGUAGE=tr_TR:tr
      - LC_ALL=tr_TR.UTF-8
      - CELERY_BROKER_URL=redis://redis:6379/0
      - TZ=Europe/Istanbul
      - FLASK_ENV=development
      - FILE_LOG_LEVEL=DEBUG
      - CONSOLE_LOG_LEVEL=INFO
      - MONGO_REST=http://mongo_rest:9000
      - ELASTICSEARCH=http://elasticsearch:9200
      - VECTORIZER=http://projecttest.westeurope.cloudapp.azure.com:9005
      - APACHE_TIKA=http://apache_tika:9998
  worker_3:
    build: ./worker
    container_name: worker_3
    command: ["celery", "worker", "-A", "application.celery", "-P", "eventlet", "--loglevel=info", "-n",
              "worker_3"]
    volumes:
      - data_log:/application/logs
      - data_worker:/application/files
    networks:
      - net_worker
      - net_mongo_rest
      - net_elasticsearch
    depends_on:
      - redis
      - gateway
    environment:
      - LANG=tr_TR.UTF-8
      - LANGUAGE=tr_TR:tr
      - LC_ALL=tr_TR.UTF-8
      - CELERY_BROKER_URL=redis://redis:6379/0
      - TZ=Europe/Istanbul
      - FLASK_ENV=development
      - FILE_LOG_LEVEL=DEBUG
      - CONSOLE_LOG_LEVEL=INFO
      - MONGO_REST=http://mongo_rest:9000
      - ELASTICSEARCH=http://elasticsearch:9200
      - VECTORIZER=http://projecttest.westeurope.cloudapp.azure.com:9005
      - APACHE_TIKA=http://apache_tika:9998
  worker_4:
    build: ./worker
    container_name: worker_4
    command: ["celery", "worker", "-A", "application.celery", "-P", "eventlet", "--loglevel=info", "-n",
              "worker_4"]
    volumes:
      - data_log:/application/logs
      - data_worker:/application/files
    networks:
      - net_worker
      - net_mongo_rest
      - net_elasticsearch
    depends_on:
      - redis
      - gateway
    environment:
      - LANG=tr_TR.UTF-8
      - LANGUAGE=tr_TR:tr
      - LC_ALL=tr_TR.UTF-8
      - CELERY_BROKER_URL=redis://redis:6379/0
      - TZ=Europe/Istanbul
      - FLASK_ENV=development
      - FILE_LOG_LEVEL=DEBUG
      - CONSOLE_LOG_LEVEL=INFO
      - MONGO_REST=http://mongo_rest:9000
      - ELASTICSEARCH=http://elasticsearch:9200
      - VECTORIZER=http://projecttest.westeurope.cloudapp.azure.com:9005
      - APACHE_TIKA=http://apache_tika:9998
  worker_5:
    build: ./worker
    container_name: worker_5
    command: ["celery", "worker", "-A", "application.celery", "-P", "eventlet", "--loglevel=info", "-n",
              "worker_5"]
    volumes:
      - data_log:/application/logs
      - data_worker:/application/files
    networks:
      - net_worker
      - net_mongo_rest
      - net_elasticsearch
    depends_on:
      - redis
      - gateway
    environment:
      - LANG=tr_TR.UTF-8
      - LANGUAGE=tr_TR:tr
      - LC_ALL=tr_TR.UTF-8
      - CELERY_BROKER_URL=redis://redis:6379/0
      - TZ=Europe/Istanbul
      - FLASK_ENV=development
      - FILE_LOG_LEVEL=DEBUG
      - CONSOLE_LOG_LEVEL=INFO
      - MONGO_REST=http://mongo_rest:9000
      - ELASTICSEARCH=http://elasticsearch:9200
      - VECTORIZER=http://projecttest.westeurope.cloudapp.azure.com:9005
      - APACHE_TIKA=http://apache_tika:9998
#  worker_6:
#    build: ./worker
#    container_name: worker_6
#    command: ["celery", "worker", "-A", "application.celery", "-P", "eventlet", "--loglevel=info", "-n",
#              "worker_6"]
#    volumes:
#      - data_log:/application/logs
#      - data_worker:/application/files
#    networks:
#      - net_worker
#      - net_mongo_rest
#      - net_elasticsearch
#    depends_on:
#      - redis
#      - gateway
#    environment:
#      - FIRST=true
#      - LANG=tr_TR.UTF-8
#      - LANGUAGE=tr_TR:tr
#      - LC_ALL=tr_TR.UTF-8
#      - CELERY_BROKER_URL=redis://redis:6379/0
#      - TZ=Europe/Istanbul
#      - FLASK_ENV=development
#      - FILE_LOG_LEVEL=DEBUG
#      - CONSOLE_LOG_LEVEL=INFO
#      - MONGO_REST=http://mongo_rest:9000
#      - ELASTICSEARCH=http://elasticsearch:9200
#      - VECTORIZER=http://projecttest.westeurope.cloudapp.azure.com:9005
#      - APACHE_TIKA=http://apache_tika:9998
#  worker_7:
#    build: ./worker
#    container_name: worker_7
#    command: ["celery", "worker", "-A", "application.celery", "-P", "eventlet", "--loglevel=info", "-n",
#              "worker_7"]
#    volumes:
#      - data_log:/application/logs
#      - data_worker:/application/files
#    networks:
#      - net_worker
#      - net_mongo_rest
#      - net_elasticsearch
#    depends_on:
#      - redis
#      - gateway
#    environment:
#      - LANG=tr_TR.UTF-8
#      - LANGUAGE=tr_TR:tr
#      - LC_ALL=tr_TR.UTF-8
#      - CELERY_BROKER_URL=redis://redis:6379/0
#      - TZ=Europe/Istanbul
#      - FLASK_ENV=development
#      - FILE_LOG_LEVEL=DEBUG
#      - CONSOLE_LOG_LEVEL=INFO
#      - MONGO_REST=http://mongo_rest:9000
#      - ELASTICSEARCH=http://elasticsearch:9200
#      - VECTORIZER=http://projecttest.westeurope.cloudapp.azure.com:9005
#      - APACHE_TIKA=http://apache_tika:9998
#  worker_8:
#    build: ./worker
#    container_name: worker_8
#    command: ["celery", "worker", "-A", "application.celery", "-P", "eventlet", "--loglevel=info", "-n",
#              "worker_8"]
#    volumes:
#      - data_log:/application/logs
#      - data_worker:/application/files
#    networks:
#      - net_worker
#      - net_mongo_rest
#      - net_elasticsearch
#    depends_on:
#      - redis
#      - gateway
#    environment:
#      - LANG=tr_TR.UTF-8
#      - LANGUAGE=tr_TR:tr
#      - LC_ALL=tr_TR.UTF-8
#      - CELERY_BROKER_URL=redis://redis:6379/0
#      - TZ=Europe/Istanbul
#      - FLASK_ENV=development
#      - FILE_LOG_LEVEL=DEBUG
#      - CONSOLE_LOG_LEVEL=INFO
#      - MONGO_REST=http://mongo_rest:9000
#      - ELASTICSEARCH=http://elasticsearch:9200
#      - VECTORIZER=http://projecttest.westeurope.cloudapp.azure.com:9005
#      - APACHE_TIKA=http://apache_tika:9998
#  worker_9:
#    build: ./worker
#    container_name: worker_9
#    command: ["celery", "worker", "-A", "application.celery", "-P", "eventlet", "--loglevel=info", "-n",
#              "worker_9"]
#    volumes:
#      - data_log:/application/logs
#      - data_worker:/application/files
#    networks:
#      - net_worker
#      - net_mongo_rest
#      - net_elasticsearch
#    depends_on:
#      - redis
#      - gateway
#    environment:
#      - LANG=tr_TR.UTF-8
#      - LANGUAGE=tr_TR:tr
#      - LC_ALL=tr_TR.UTF-8
#      - CELERY_BROKER_URL=redis://redis:6379/0
#      - TZ=Europe/Istanbul
#      - FLASK_ENV=development
#      - FILE_LOG_LEVEL=DEBUG
#      - CONSOLE_LOG_LEVEL=INFO
#      - MONGO_REST=http://mongo_rest:9000
#      - ELASTICSEARCH=http://elasticsearch:9200
#      - VECTORIZER=http://projecttest.westeurope.cloudapp.azure.com:9005
#      - APACHE_TIKA=http://apache_tika:9998
#  worker_10:
#    build: ./worker
#    container_name: worker_10
#    command: ["celery", "worker", "-A", "application.celery", "-P", "eventlet", "--loglevel=info", "-n",
#              "worker_10"]
#    volumes:
#      - data_log:/application/logs
#      - data_worker:/application/files
#    networks:
#      - net_worker
#      - net_mongo_rest
#      - net_elasticsearch
#    depends_on:
#      - redis
#      - gateway
#    environment:
#      - LANG=tr_TR.UTF-8
#      - LANGUAGE=tr_TR:tr
#      - LC_ALL=tr_TR.UTF-8
#      - CELERY_BROKER_URL=redis://redis:6379/0
#      - TZ=Europe/Istanbul
#      - FLASK_ENV=development
#      - FILE_LOG_LEVEL=DEBUG
#      - CONSOLE_LOG_LEVEL=INFO
#      - MONGO_REST=http://mongo_rest:9000
#      - ELASTICSEARCH=http://elasticsearch:9200
#      - VECTORIZER=http://projecttest.westeurope.cloudapp.azure.com:9005
#      - APACHE_TIKA=http://apache_tika:9998
volumes:
  data_log:
  data_mongo:
  data_redis:
  data_worker:
  data_embeddings:

networks:
  net_mongo:
  net_worker:
  net_mongo_rest:
  net_elasticsearch:
